### ISSUE TITLE
Errors occur when running Q-testing tool (version released in 2020-12-24)

### ISSUE THREAD

**Issue by Joseph9Morgan** [anlalalu/Q-testing#11]
We have encountered an error when running the newest version of Q-testing tool released on 2020-12-24. Our running environment is in Ubuntu 20.04 and Ubuntu 18.04. However, on both systems the following error occured when we tried to run the testing tool:
````
Traceback (most recent call last):
  File "main.py", line 170, in <module>
  File "ConfigParser.py", line 618, in get
ConfigParser.NoOptionError: No option 'test_index' in section: 'Setting'
Failed to execute script main
````
We have checked our CONF.txt accordingly, and the same CONF.txt worked just fine using the older version of Q-testing which was released in 2020-12-10. We wonder if there is a small change in the CONF.txt setting, where it needs a "test_index" option as indicated by the traceback message.

**Comment by limerick1718** [comment]
Dear Joseph,

Have you solved this problem?
I also encounter this problem. Would you please kindly share your solution with us?

Many thanks :)

**Comment by Joseph9Morgan** [comment]
> Dear Joseph,
> 
> Have you solved this problem? I also encounter this problem. Would you please kindly share your solution with us?
> 
> Many thanks :)

Hi there! Sorry I missed your problem. I haven't solved the issue yet,  but i tried to make it work with some apps when i set the test_index to a fixed value such as one(you could try some other fix values), and it could be running for some time but won't last for long. We have tried to make contact with the author but get no replies. If you have any other problems, do ask me about them, I'll be happy to help.
