### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by RichardHoOoOo** [anlalalu/Q-testing#3]
Hi, I encountered this issue when running `./Q-testing/main -r CONF.txt`

```
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/tim/PyCharmProject/Q-testing/venv/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
  File "/home/tim/PyCharmProject/Q-testing/Q-testing/qlearning_final_coverage_multi.py", line 21, in <module>
  File "/home/tim/PyCharmProject/Q-testing/venv/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
  File "/home/tim/PyCharmProject/Q-testing/venv/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
  File "/home/tim/PyCharmProject/Q-testing/venv/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
  File "/home/tim/PyCharmProject/Q-testing/venv/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
  File "/home/tim/PyCharmProject/Q-testing/venv/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
  File "/home/tim/PyCharmProject/Q-testing/venv/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
ImportError: Traceback (most recent call last):
  File "/home/tim/PyCharmProject/Q-testing/venv/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
  File "/home/tim/PyCharmProject/Q-testing/venv/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
  File "/home/tim/PyCharmProject/Q-testing/venv/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
  File "/home/tim/PyCharmProject/Q-testing/venv/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 20, in swig_import_helper
  File "/home/tim/PyCharmProject/Q-testing/venv/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 517, in load_module
ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home1/jhuao/FSE2020/tool/Q-testing/Q-testing/libstdc++.so.6)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
main returned -1
```

May I ask how to fix it?

**Comment by tingsu** [comment]
I have not ever encountered this issue when I run this tool.

**Comment by RichardHoOoOo** [comment]
Hi @tingsu , this one has been fixed after we upgrade our servers' OS. It seems Q-Tesing is not compatible with some old OS versions.
